### ISSUE TITLE
Missing helper

### ISSUE THREAD

**Issue by mctdi** [solidgoldpig/handlebars.moment#2]
Hi

In my file in imported script

```
    <script src="js/moment.js" type="text/javascript"></script>
    <script src="js/handlebars.min.js" type="text/javascript" ></script>
    <script src="js/handlebars.moment.js" type="text/javascript" ></script>
```

In my template, i do

```
{{moment birthdate "L"}}
```

But i get

Uncaught Error: Missing helper: "moment"

is there any other thing to do?

**Comment by solidgoldpig** [comment]
The handlebars-moment module is written in AMD/CommonJS style and therefore needs to be loaded via an AMD loader in a browser, eg, [RequireJS](http://requirejs.org/). As the section `Registering the helpers` shows:

    var Handlebars = require("handlebars");
    var MomentHandler = require("handlebars.moment");
    MomentHandler.registerHelpers(Handlebars);

`handlebars.moment` returns an object which has the method that you need to call to register its helper methods on `handlebars`. If you just load the file, nothing will happen.
